import os

LANG_NAMES = {
    "pt": "Português (Brasil)",
    "en": "English",
    "es": "Español",
    "fr": "Français",
    "de": "Deutsch",
}

LANGS = {
    "pt": {
        "app_title": "Gerenciador de contas Roblox",
        "menu_file": "&Arquivo",
        "menu_help": "A&juda",
        "act_add": "Adicionar conta",
        "act_edit": "Editar conta",
        "act_remove": "Remover conta",
        "act_login": "Abrir para login",
        "act_launch": "Entrar no jogo com as selecionadas",
        "act_lock": "Bloquear",
        "act_settings": "Configurações",
        "act_quit": "Sair",
        "act_guide": "Guia rápido",
        "act_about": "Sobre",
        "col_group": "Grupo",
        "col_last": "Última entrada",
        "col_notes": "Notas",
        "btn_add": "Adicionar",
        "btn_edit": "Editar",
        "btn_remove": "Remover",
        "btn_login": "Abrir para login",
        "btn_settings": "Configurações",
        "btn_launch": "Entrar com as selecionadas",
        "btn_lock": "Bloquear",
        "ph_place": "ID do jogo (placeId)",
        "ph_job": "ID do servidor (opcional)",
        "delay_suffix": " s entre contas",
        "accounts_list": "Lista de contas",
        "never": "—",
        "dlg_add": "Adicionar conta",
        "dlg_edit": "Editar conta",
        "lbl_group": "Grupo",
        "lbl_notes": "Notas",
        "warn_noacc_title": "Nenhuma conta",
        "warn_noacc": "Selecione ao menos uma conta na lista.",
        "warn_game_title": "Dados inválidos",
        "warn_game": "O ID do jogo deve conter apenas números (até 19 dígitos).",
        "warn_job": "O ID do servidor deve ter o formato 00000000-0000-0000-0000-000000000000.",
        "warn_many_title": "Muitas contas",
        "warn_many": "O limite por lote é {n} contas. Ajuste em Configurações > Segurança.",
        "ask_many_title": "Confirmar",
        "ask_many": "Abrir o cliente para {n} contas agora?",
        "ask_remove_title": "Remover",
        "ask_remove": "Remover {n} conta(s) da lista?",
        "chk_delete_profile": "Apagar também o login salvo (perfil) dessas contas",
        "settings_title": "Configurações",
        "tab_general": "Geral",
        "tab_security": "Segurança",
        "tab_access": "Acessibilidade e idioma",
        "lbl_client": "Cliente",
        "lbl_command": "Comando",
        "hint_command": "Use {uri} onde o link do jogo deve entrar. Só é editável em “Personalizado”, depois de permitir comandos personalizados na aba Segurança.",
        "lbl_language": "Idioma",
        "lang_auto": "Automático (idioma do sistema)",
        "lbl_font": "Tamanho do texto",
        "font_small": "Pequeno",
        "font_normal": "Normal",
        "font_large": "Grande",
        "font_xlarge": "Muito grande",
        "lbl_theme": "Aparência",
        "theme_system": "Padrão do sistema",
        "theme_light": "Claro",
        "theme_dark": "Escuro",
        "theme_hc_dark": "Alto contraste (escuro)",
        "theme_hc_light": "Alto contraste (claro)",
        "chk_custom": "Permitir comando personalizado (avançado)",
        "hint_custom": "Atenção: um comando personalizado roda como você. Use só comandos que você conhece.",
        "lbl_maxbatch": "Máximo de contas por vez",
        "lbl_idle": "Bloquear após inatividade",
        "idle_suffix": " min",
        "idle_off": "Nunca",
        "btn_wipe": "Apagar todos os meus dados…",
        "ask_wipe_title": "Apagar tudo",
        "pw_mismatch": "As senhas não conferem.",
        "lock_title": "Programa bloqueado",
        "lock_wrong": "Senha incorreta.",
        "lock_wait": "Muitas tentativas. Aguarde {n} s.",
        "btn_unlock": "Desbloquear",
        "btn_quit": "Sair",
        "custom_blocked": "Comando personalizado recusado: {why}",
        "why_invalid": "formato inválido (precisa conter {uri})",
        "why_blocked": "programa não permitido (shell/interpretador)",
        "client_missing_title": "Cliente não encontrado",
        "client_missing": "Não encontrei “{name}” neste computador. Instale o cliente (Sober ou Mocktail) ou escolha outro em Configurações.",
        "err_title": "Algo deu errado",
        "err_generic": "Ocorreu um erro inesperado. Os detalhes técnicos foram salvos em:\n{path}",
        "root_refuse": "Por segurança, este programa não deve ser executado como administrador (root).",
        "guide_title": "Guia rápido",
        "about_title": "Sobre",
        "log_panel": "Mensagens",
        "log_ready": "Pronto. Adicione uma conta e use “Abrir para login” na primeira vez.",
        "log_cmd": "{name}: {cmd}",
        "log_output": "   saída do cliente em: {path}",
        "log_login_hint": "Entre na conta dentro do cliente e feche-o. O login fica salvo neste perfil.",
        "log_done": "Todas as contas foram iniciadas.",
        "log_failed": "{name}: não foi possível iniciar o cliente.",
        "log_profile_deleted": "Perfil apagado: {name}.",
        "err_dir_owner": "A pasta pertence a outro usuário: {path}",
        "err_not_file": "O caminho não é um arquivo comum.",
        "err_too_big": "Arquivo grande demais.",
        "err_username": "Usuário inválido (3 a 20 caracteres: letras, números e _).",
        "err_password_type": "Senha inválida.",
        "err_password_long": "Senha longa demais (máximo 200 caracteres).",
        "err_password_control": "A senha contém caracteres de controle.",
        "err_master_short": "A senha mestra precisa ter pelo menos {n} caracteres.",
        "err_vault_content": "Conteúdo do cofre inválido.",
        "err_vault_exists": "Já existe um cofre neste local.",
        "err_vault_version": "Versão de cofre não suportada.",
        "err_vault_corrupt": "O arquivo do cofre está ilegível ou corrompido.",
        "err_wrong_master": "Senha mestra incorreta.",
        "err_crypto": "Dados criptografados inválidos.",
        "err_not_found": "Conta não encontrada.",
        "err_exists": "Já existe uma conta chamada {name}.",
        "err_limit": "Limite de {n} contas atingido.",
        "err_import_lines": "O arquivo tem linhas demais (máximo {n}).",
        "err_import_format": "formato esperado: usuario:senha",
        "err_import_utf8": "O arquivo precisa estar em UTF-8.",
        "err_import_read": "Não foi possível ler o arquivo: {why}",
        "err_write": "Não foi possível gravar o arquivo: {why}",
        "err_session_path": "Caminho de sessão inválido.",
        "err_symlink": "Há um link simbólico dentro da pasta do Sober; operação recusada.",
        "err_account_id": "Identificador de conta inválido.",
        "err_session_read": "Falha ao ler a sessão: {why}",
        "err_profile_outside": "O perfil está fora da pasta de perfis; operação recusada.",
        "err_flatpak_missing": "O flatpak não foi encontrado neste computador.",
        "err_flatpak_query": "Falha ao consultar o flatpak: {why}",
        "err_sober_missing": "O Sober não está instalado via flatpak.",
        "err_sober_running": "O Sober já está em execução. Feche-o antes de trocar de conta.",
        "err_custom_denied": "Comando personalizado não permitido.",
        "err_swap_client": "Sem perfis separados, a troca de sessão só funciona com o Sober (Flatpak).",
        "err_client_start": "Não foi possível iniciar o cliente: {why}",
        "err_deps": "Dependência ausente. Rode: pip install -r requirements.txt",
        "err_attempts": "Número máximo de tentativas atingido.",
        "err_no_accounts": "Nenhuma conta cadastrada.",
        "log_vault_created": "Cofre criado.",
        "log_vault_unlocked": "Cofre desbloqueado ({n} conta(s)).",
        "log_unlock_fail": "Senha mestra incorreta (tentativa {n}).",
        "log_locked": "Programa bloqueado.",
        "log_idle_lock": "Bloqueio automático por inatividade.",
        "log_unlocked": "Programa desbloqueado.",
        "log_master_changed": "Senha mestra alterada.",
        "log_migrated": "{n} conta(s) da versão anterior foram migradas para o cofre.",
        "log_added": "Conta adicionada: {name}.",
        "log_updated": "Conta atualizada: {name}.",
        "log_removed": "Conta removida: {name}.",
        "log_import_read": "Lendo arquivo de importação: {path}",
        "log_import_text": "Lendo as contas coladas.",
        "log_import_line": "Linha {n} ignorada: {why}",
        "log_import_more": "… e mais {n} linha(s) inválida(s).",
        "log_import_none": "Nenhuma conta válida encontrada.",
        "log_import_done": "Importação concluída: {added} nova(s), {updated} atualizada(s), {skipped} mantida(s), {duplicated} repetida(s) no arquivo, {invalid} linha(s) inválida(s).",
        "log_export_done": "{n} conta(s) exportada(s) para: {path}",
        "log_export_warn": "O arquivo exportado contém senhas em texto puro. Apague-o depois de usar.",
        "log_pw_shown": "Senha de {name} exibida na tela.",
        "log_pw_copied": "Senha de {name} copiada; será apagada da área de transferência em {n} s.",
        "log_clip_cleared": "Área de transferência limpa.",
        "log_launch": "Abrindo o cliente com a conta: {name}",
        "log_client_exit": "{name}: o cliente encerrou logo após abrir (código {code}). Veja {path}",
        "log_session_prev": "Sessão atual guardada na conta: {name}",
        "log_session_backup": "Sessão anterior sem conta guardada como backup criptografado.",
        "log_session_restored": "Sessão restaurada para a conta: {name}",
        "log_session_missing": "A conta {name} ainda não tem sessão salva; faça login no Sober.",
        "log_session_saved": "Sessão salva para a conta: {name}",
        "log_session_none": "Nenhuma sessão do Sober encontrada para salvar.",
        "log_session_isolated": "Com perfis separados cada conta já guarda a própria sessão; esta ação só vale sem perfis separados.",
        "log_settings_corrupt": "O arquivo de configurações estava corrompido; foi guardado como .corrupt e as configurações padrão foram restauradas.",
        "log_settings_saved": "Configurações salvas.",
        "log_exit": "Encerrando.",
        "log_interrupted": "Interrompido.",
        "log_unhandled": "Erro inesperado. Detalhes em: {path}",
        "log_count": "{n} conta(s) cadastrada(s).",
        "col_user": "Usuário",
        "col_password": "Senha",
        "btn_copy": "Copiar senha",
        "act_copy": "Copiar senha",
        "act_show": "Mostrar senha…",
        "act_import": "Importar contas de um arquivo…",
        "act_import_text": "Importar contas colando texto…",
        "act_export": "Exportar contas…",
        "act_save_session": "Salvar a sessão atual do Sober na conta ativa",
        "ph_search": "Buscar por usuário, grupo ou nota",
        "ph_keep_pw": "Deixe em branco para manter a senha atual",
        "chk_clear_pw": "Remover a senha guardada",
        "chk_show_pw": "Mostrar o que estou digitando",
        "hint_add": "A senha é opcional e fica guardada criptografada no cofre. Para entrar na conta, use “Abrir para login” uma vez e faça o login dentro do cliente.",
        "warn_title": "Atenção",
        "warn_user_title": "Usuário inválido",
        "warn_nopw_title": "Sem senha",
        "warn_nopw": "Essa conta não tem senha guardada.",
        "warn_swap_one": "Sem perfis separados só dá para usar uma conta por vez.",
        "dlg_create_title": "Criar cofre",
        "create_prompt": "Crie a senha mestra. Ela protege todas as senhas e sessões guardadas e não pode ser recuperada se for esquecida.",
        "lbl_master": "Senha mestra",
        "lbl_master_repeat": "Repita a senha mestra",
        "chk_isolate": "Perfil separado por conta (recomendado; permite várias contas abertas ao mesmo tempo)",
        "sec_privacy": "Privacidade: este programa não usa a internet nem envia dados. As senhas ficam criptografadas no cofre (senha mestra) e todas as pastas do programa são privadas (somente você acessa).",
        "hint_lock": "O bloqueio esconde a janela até a senha mestra ser digitada. Os logins dos perfis separados ficam nas pastas do próprio cliente e não são criptografados por este programa; use criptografia de disco para protegê-los.",
        "btn_changemaster": "Alterar senha mestra…",
        "ask_wipe": "Isto apaga o cofre com todas as contas e senhas, os perfis e logins salvos, as sessões, os logs e as configurações. Não dá para desfazer. Continuar?",
        "info_wipe_done": "Todos os dados do programa foram apagados. O programa será fechado.",
        "pw_current": "Digite a senha mestra:",
        "pw_confirm": "Confirme a senha mestra:",
        "pw_title": "Senha mestra",
        "pw_new": "Nova senha mestra (mínimo 8 caracteres):",
        "pw_repeat": "Repita a nova senha mestra:",
        "lock_prompt": "Digite a senha mestra para continuar:",
        "dlg_secret_title": "Senha de {name}",
        "pw_none": "(sem senha cadastrada)",
        "import_title": "Importar contas",
        "import_filter": "Arquivos de texto (*.txt);;Todos os arquivos (*)",
        "import_text_hint": "Cole uma conta por linha, no formato usuario:senha.",
        "ask_overwrite_title": "Contas existentes",
        "ask_overwrite": "{n} conta(s) já existem no cofre. Substituir a senha delas pela importada?",
        "export_title": "Exportar contas",
        "ask_export": "O arquivo exportado terá todas as senhas em texto puro. Continuar?",
        "guide_text": "1. Em Adicionar, informe o usuário (e a senha, se quiser guardá-la).\n2. Para trazer várias contas de uma vez, use Arquivo > Importar, com uma conta por linha no formato usuario:senha. O mesmo formato vale para exportar.\n3. Selecione a conta e clique em “Abrir para login”. Entre na conta dentro do cliente (Sober ou Mocktail) e feche-o. Isso é feito uma vez por conta.\n4. Digite o ID do jogo (o número na URL da página do jogo em roblox.com), selecione as contas e clique em “Entrar com as selecionadas”.\n5. Para colar a senha no login, use “Copiar senha”: ela é apagada da área de transferência em {n} segundos.\n\nAtalhos: Ctrl+N adicionar, Ctrl+E editar, Delete remover, Ctrl+Shift+C copiar senha, Ctrl+I importar, Ctrl+Shift+E exportar, Ctrl+Enter entrar no jogo, Ctrl+L bloquear, Ctrl+, configurações, F1 este guia.\n\nTudo o que acontece também aparece no terminal e no arquivo de log. Senhas nunca são registradas.",
        "about_text": "Gerenciador de contas Roblox {version}\nProjeto independente, sem vínculo com a Roblox Corporation.\nNão usa a internet e não envia dados.",
        "cli_desc": "Gerenciador de contas Roblox para Linux. Sem comando, abre a interface gráfica.",
        "cli_list": "lista as contas",
        "cli_add": "adiciona uma conta",
        "cli_remove": "remove uma conta",
        "cli_import": "importa contas de um arquivo usuario:senha",
        "cli_export": "exporta as contas para um arquivo usuario:senha",
        "cli_launch": "abre o cliente com uma conta",
        "cli_version": "mostra a versão",
        "cli_yes": "não pede confirmação",
        "cli_overwrite": "substitui a senha das contas que já existem",
        "cli_force": "substitui o arquivo de destino se ele existir",
        "cli_account": "usuário da conta",
        "cli_file": "caminho do arquivo",
        "cli_prompt_master": "Senha mestra: ",
        "cli_prompt_confirm": "Confirme a senha mestra: ",
        "cli_prompt_new": "Crie a senha mestra: ",
        "cli_prompt_repeat": "Repita a senha mestra: ",
        "cli_prompt_pass": "Senha (vazio para nenhuma): ",
        "cli_confirm_remove": "Remover {name}? [s/N]: ",
        "cli_confirm_replace": "{path} já existe. Substituir? [s/N]: ",
        "cli_confirm_overwrite": "{n} conta(s) já existem. Substituir as senhas? [s/N]: ",
    },
    "en": {
        "app_title": "Roblox Account Manager",
        "menu_file": "&File",
        "menu_help": "&Help",
        "act_add": "Add account",
        "act_edit": "Edit account",
        "act_remove": "Remove account",
        "act_login": "Open to sign in",
        "act_launch": "Join game with selected accounts",
        "act_lock": "Lock",
        "act_settings": "Settings",
        "act_quit": "Quit",
        "act_guide": "Quick guide",
        "act_about": "About",
        "col_group": "Group",
        "col_last": "Last joined",
        "col_notes": "Notes",
        "btn_add": "Add",
        "btn_edit": "Edit",
        "btn_remove": "Remove",
        "btn_login": "Open to sign in",
        "btn_settings": "Settings",
        "btn_launch": "Join with selected",
        "btn_lock": "Lock",
        "ph_place": "Game ID (placeId)",
        "ph_job": "Server ID (optional)",
        "delay_suffix": " s between accounts",
        "accounts_list": "Account list",
        "never": "—",
        "dlg_add": "Add account",
        "dlg_edit": "Edit account",
        "lbl_group": "Group",
        "lbl_notes": "Notes",
        "warn_noacc_title": "No account",
        "warn_noacc": "Select at least one account in the list.",
        "warn_game_title": "Invalid data",
        "warn_game": "The game ID must contain only digits (up to 19).",
        "warn_job": "The server ID must look like 00000000-0000-0000-0000-000000000000.",
        "warn_many_title": "Too many accounts",
        "warn_many": "The limit per batch is {n} accounts. Change it in Settings > Security.",
        "ask_many_title": "Confirm",
        "ask_many": "Open the client for {n} accounts now?",
        "ask_remove_title": "Remove",
        "ask_remove": "Remove {n} account(s) from the list?",
        "chk_delete_profile": "Also delete the saved login (profile) of these accounts",
        "settings_title": "Settings",
        "tab_general": "General",
        "tab_security": "Security",
        "tab_access": "Accessibility and language",
        "lbl_client": "Client",
        "lbl_command": "Command",
        "hint_command": "Use {uri} where the game link goes. Editable only for “Custom”, after allowing custom commands in the Security tab.",
        "lbl_language": "Language",
        "lang_auto": "Automatic (system language)",
        "lbl_font": "Text size",
        "font_small": "Small",
        "font_normal": "Normal",
        "font_large": "Large",
        "font_xlarge": "Extra large",
        "lbl_theme": "Appearance",
        "theme_system": "System default",
        "theme_light": "Light",
        "theme_dark": "Dark",
        "theme_hc_dark": "High contrast (dark)",
        "theme_hc_light": "High contrast (light)",
        "chk_custom": "Allow custom command (advanced)",
        "hint_custom": "Warning: a custom command runs as you. Only use commands you understand.",
        "lbl_maxbatch": "Maximum accounts at once",
        "lbl_idle": "Lock after inactivity",
        "idle_suffix": " min",
        "idle_off": "Never",
        "btn_wipe": "Erase all my data…",
        "ask_wipe_title": "Erase everything",
        "pw_mismatch": "The passwords do not match.",
        "lock_title": "Program locked",
        "lock_wrong": "Wrong password.",
        "lock_wait": "Too many attempts. Wait {n} s.",
        "btn_unlock": "Unlock",
        "btn_quit": "Quit",
        "custom_blocked": "Custom command rejected: {why}",
        "why_invalid": "invalid format (must contain {uri})",
        "why_blocked": "program not allowed (shell/interpreter)",
        "client_missing_title": "Client not found",
        "client_missing": "I could not find “{name}” on this computer. Install the client (Sober or Mocktail) or pick another one in Settings.",
        "err_title": "Something went wrong",
        "err_generic": "An unexpected error occurred. Technical details were saved to:\n{path}",
        "root_refuse": "For safety, this program should not be run as administrator (root).",
        "guide_title": "Quick guide",
        "about_title": "About",
        "log_panel": "Messages",
        "log_ready": "Ready. Add an account and use “Open to sign in” the first time.",
        "log_cmd": "{name}: {cmd}",
        "log_output": "   client output in: {path}",
        "log_login_hint": "Sign in inside the client and close it. The login is saved in this profile.",
        "log_done": "All accounts have been started.",
        "log_failed": "{name}: could not start the client.",
        "log_profile_deleted": "Profile deleted: {name}.",
        "err_dir_owner": "The folder belongs to another user: {path}",
        "err_not_file": "The path is not a regular file.",
        "err_too_big": "File too large.",
        "err_username": "Invalid username (3 to 20 characters: letters, numbers and _).",
        "err_password_type": "Invalid password.",
        "err_password_long": "Password too long (200 characters at most).",
        "err_password_control": "The password contains control characters.",
        "err_master_short": "The master password must have at least {n} characters.",
        "err_vault_content": "Invalid vault contents.",
        "err_vault_exists": "A vault already exists here.",
        "err_vault_version": "Unsupported vault version.",
        "err_vault_corrupt": "The vault file is unreadable or corrupted.",
        "err_wrong_master": "Wrong master password.",
        "err_crypto": "Invalid encrypted data.",
        "err_not_found": "Account not found.",
        "err_exists": "An account named {name} already exists.",
        "err_limit": "Limit of {n} accounts reached.",
        "err_import_lines": "The file has too many lines ({n} at most).",
        "err_import_format": "expected format: username:password",
        "err_import_utf8": "The file must be UTF-8 encoded.",
        "err_import_read": "Could not read the file: {why}",
        "err_write": "Could not write the file: {why}",
        "err_session_path": "Invalid session path.",
        "err_symlink": "A symbolic link was found inside the Sober folder; operation refused.",
        "err_account_id": "Invalid account identifier.",
        "err_session_read": "Failed to read the session: {why}",
        "err_profile_outside": "The profile is outside the profiles folder; operation refused.",
        "err_flatpak_missing": "flatpak was not found on this computer.",
        "err_flatpak_query": "Failed to query flatpak: {why}",
        "err_sober_missing": "Sober is not installed through flatpak.",
        "err_sober_running": "Sober is already running. Close it before switching accounts.",
        "err_custom_denied": "Custom command not allowed.",
        "err_swap_client": "Without separate profiles, session switching only works with Sober (Flatpak).",
        "err_client_start": "Could not start the client: {why}",
        "err_deps": "Missing dependency. Run: pip install -r requirements.txt",
        "err_attempts": "Maximum number of attempts reached.",
        "err_no_accounts": "No accounts registered.",
        "log_vault_created": "Vault created.",
        "log_vault_unlocked": "Vault unlocked ({n} account(s)).",
        "log_unlock_fail": "Wrong master password (attempt {n}).",
        "log_locked": "Application locked.",
        "log_idle_lock": "Locked automatically after inactivity.",
        "log_unlocked": "Application unlocked.",
        "log_master_changed": "Master password changed.",
        "log_migrated": "{n} account(s) from the previous version were migrated to the vault.",
        "log_added": "Account added: {name}.",
        "log_updated": "Account updated: {name}.",
        "log_removed": "Account removed: {name}.",
        "log_import_read": "Reading import file: {path}",
        "log_import_text": "Reading the pasted accounts.",
        "log_import_line": "Line {n} ignored: {why}",
        "log_import_more": "… and {n} more invalid line(s).",
        "log_import_none": "No valid accounts found.",
        "log_import_done": "Import finished: {added} new, {updated} updated, {skipped} kept, {duplicated} repeated in the file, {invalid} invalid line(s).",
        "log_export_done": "{n} account(s) exported to: {path}",
        "log_export_warn": "The exported file contains plain-text passwords. Delete it after use.",
        "log_pw_shown": "Password of {name} shown on screen.",
        "log_pw_copied": "Password of {name} copied; it will be cleared from the clipboard in {n} s.",
        "log_clip_cleared": "Clipboard cleared.",
        "log_launch": "Opening the client with account: {name}",
        "log_client_exit": "{name}: the client exited right after starting (code {code}). See {path}",
        "log_session_prev": "Current session stored for account: {name}",
        "log_session_backup": "Previous session without an account stored as an encrypted backup.",
        "log_session_restored": "Session restored for account: {name}",
        "log_session_missing": "Account {name} has no saved session yet; log in on Sober.",
        "log_session_saved": "Session saved for account: {name}",
        "log_session_none": "No Sober session found to save.",
        "log_session_isolated": "With separate profiles each account already keeps its own session; this action only applies without separate profiles.",
        "log_settings_corrupt": "The settings file was corrupted; it was kept as .corrupt and the defaults were restored.",
        "log_settings_saved": "Settings saved.",
        "log_exit": "Exiting.",
        "log_interrupted": "Interrupted.",
        "log_unhandled": "Unexpected error. Details in: {path}",
        "log_count": "{n} account(s) registered.",
        "col_user": "Username",
        "col_password": "Password",
        "btn_copy": "Copy password",
        "act_copy": "Copy password",
        "act_show": "Show password…",
        "act_import": "Import accounts from a file…",
        "act_import_text": "Import accounts by pasting text…",
        "act_export": "Export accounts…",
        "act_save_session": "Save the current Sober session to the active account",
        "ph_search": "Search by username, group or note",
        "ph_keep_pw": "Leave blank to keep the current password",
        "chk_clear_pw": "Remove the stored password",
        "chk_show_pw": "Show what I am typing",
        "hint_add": "The password is optional and is stored encrypted in the vault. To sign in to the account, use “Open to sign in” once and log in inside the client.",
        "warn_title": "Notice",
        "warn_user_title": "Invalid username",
        "warn_nopw_title": "No password",
        "warn_nopw": "This account has no stored password.",
        "warn_swap_one": "Without separate profiles only one account can be used at a time.",
        "dlg_create_title": "Create vault",
        "create_prompt": "Create the master password. It protects every stored password and session and cannot be recovered if forgotten.",
        "lbl_master": "Master password",
        "lbl_master_repeat": "Repeat the master password",
        "chk_isolate": "Separate profile per account (recommended; allows several accounts open at once)",
        "sec_privacy": "Privacy: this program does not use the internet or send any data. Passwords are encrypted in the vault (master password) and every folder of the program is private (only you can access it).",
        "hint_lock": "Locking hides the window until the master password is entered. Logins of separate profiles live in the client's own folders and are not encrypted by this program; use disk encryption to protect them.",
        "btn_changemaster": "Change master password…",
        "ask_wipe": "This deletes the vault with all accounts and passwords, the profiles and saved logins, the sessions, the logs and the settings. It cannot be undone. Continue?",
        "info_wipe_done": "All program data has been deleted. The program will now close.",
        "pw_current": "Enter the master password:",
        "pw_confirm": "Confirm the master password:",
        "pw_title": "Master password",
        "pw_new": "New master password (at least 8 characters):",
        "pw_repeat": "Repeat the new master password:",
        "lock_prompt": "Enter the master password to continue:",
        "dlg_secret_title": "Password of {name}",
        "pw_none": "(no password stored)",
        "import_title": "Import accounts",
        "import_filter": "Text files (*.txt);;All files (*)",
        "import_text_hint": "Paste one account per line, in the format username:password.",
        "ask_overwrite_title": "Existing accounts",
        "ask_overwrite": "{n} account(s) already exist in the vault. Replace their password with the imported one?",
        "export_title": "Export accounts",
        "ask_export": "The exported file will contain all passwords in plain text. Continue?",
        "guide_text": "1. Under Add, enter the username (and the password, if you want to store it).\n2. To bring in many accounts at once, use File > Import, with one account per line in the format username:password. The same format is used to export.\n3. Select the account and click “Open to sign in”. Log in inside the client (Sober or Mocktail) and close it. This is done once per account.\n4. Enter the game ID (the number in the game page URL on roblox.com), select the accounts and click “Join with selected”.\n5. To paste the password at login, use “Copy password”: it is cleared from the clipboard after {n} seconds.\n\nShortcuts: Ctrl+N add, Ctrl+E edit, Delete remove, Ctrl+Shift+C copy password, Ctrl+I import, Ctrl+Shift+E export, Ctrl+Enter join game, Ctrl+L lock, Ctrl+, settings, F1 this guide.\n\nEverything that happens also shows up in the terminal and in the log file. Passwords are never logged.",
        "about_text": "Roblox account manager {version}\nIndependent project, not affiliated with Roblox Corporation.\nIt does not use the internet and does not send data.",
        "cli_desc": "Roblox account manager for Linux. Without a command, opens the graphical interface.",
        "cli_list": "list the accounts",
        "cli_add": "add an account",
        "cli_remove": "remove an account",
        "cli_import": "import accounts from a username:password file",
        "cli_export": "export the accounts to a username:password file",
        "cli_launch": "open the client with an account",
        "cli_version": "show the version",
        "cli_yes": "do not ask for confirmation",
        "cli_overwrite": "replace the password of accounts that already exist",
        "cli_force": "overwrite the destination file if it exists",
        "cli_account": "account username",
        "cli_file": "file path",
        "cli_prompt_master": "Master password: ",
        "cli_prompt_confirm": "Confirm the master password: ",
        "cli_prompt_new": "Create the master password: ",
        "cli_prompt_repeat": "Repeat the master password: ",
        "cli_prompt_pass": "Password (empty for none): ",
        "cli_confirm_remove": "Remove {name}? [y/N]: ",
        "cli_confirm_replace": "{path} already exists. Replace it? [y/N]: ",
        "cli_confirm_overwrite": "{n} account(s) already exist. Replace their passwords? [y/N]: ",
    },
    "es": {
        "app_title": "Gestor de cuentas de Roblox",
        "menu_file": "&Archivo",
        "menu_help": "A&yuda",
        "act_add": "Añadir cuenta",
        "act_edit": "Editar cuenta",
        "act_remove": "Quitar cuenta",
        "act_login": "Abrir para iniciar sesión",
        "act_launch": "Entrar al juego con las seleccionadas",
        "act_lock": "Bloquear",
        "act_settings": "Ajustes",
        "act_quit": "Salir",
        "act_guide": "Guía rápida",
        "act_about": "Acerca de",
        "col_group": "Grupo",
        "col_last": "Última entrada",
        "col_notes": "Notas",
        "btn_add": "Añadir",
        "btn_edit": "Editar",
        "btn_remove": "Quitar",
        "btn_login": "Abrir para iniciar sesión",
        "btn_settings": "Ajustes",
        "btn_launch": "Entrar con las seleccionadas",
        "btn_lock": "Bloquear",
        "ph_place": "ID del juego (placeId)",
        "ph_job": "ID del servidor (opcional)",
        "delay_suffix": " s entre cuentas",
        "accounts_list": "Lista de cuentas",
        "never": "—",
        "dlg_add": "Añadir cuenta",
        "dlg_edit": "Editar cuenta",
        "lbl_group": "Grupo",
        "lbl_notes": "Notas",
        "warn_noacc_title": "Ninguna cuenta",
        "warn_noacc": "Selecciona al menos una cuenta de la lista.",
        "warn_game_title": "Datos no válidos",
        "warn_game": "El ID del juego solo puede tener números (hasta 19 dígitos).",
        "warn_job": "El ID del servidor debe tener el formato 00000000-0000-0000-0000-000000000000.",
        "warn_many_title": "Demasiadas cuentas",
        "warn_many": "El límite por lote es de {n} cuentas. Cámbialo en Ajustes > Seguridad.",
        "ask_many_title": "Confirmar",
        "ask_many": "¿Abrir el cliente para {n} cuentas ahora?",
        "ask_remove_title": "Quitar",
        "ask_remove": "¿Quitar {n} cuenta(s) de la lista?",
        "chk_delete_profile": "Borrar también la sesión guardada (perfil) de estas cuentas",
        "settings_title": "Ajustes",
        "tab_general": "General",
        "tab_security": "Seguridad",
        "tab_access": "Accesibilidad e idioma",
        "lbl_client": "Cliente",
        "lbl_command": "Comando",
        "hint_command": "Usa {uri} donde va el enlace del juego. Solo se edita en “Personalizado”, tras permitir comandos personalizados en la pestaña Seguridad.",
        "lbl_language": "Idioma",
        "lang_auto": "Automático (idioma del sistema)",
        "lbl_font": "Tamaño del texto",
        "font_small": "Pequeño",
        "font_normal": "Normal",
        "font_large": "Grande",
        "font_xlarge": "Muy grande",
        "lbl_theme": "Apariencia",
        "theme_system": "Predeterminado del sistema",
        "theme_light": "Claro",
        "theme_dark": "Oscuro",
        "theme_hc_dark": "Alto contraste (oscuro)",
        "theme_hc_light": "Alto contraste (claro)",
        "chk_custom": "Permitir comando personalizado (avanzado)",
        "hint_custom": "Atención: un comando personalizado se ejecuta como tú. Usa solo comandos que conozcas.",
        "lbl_maxbatch": "Máximo de cuentas a la vez",
        "lbl_idle": "Bloquear tras inactividad",
        "idle_suffix": " min",
        "idle_off": "Nunca",
        "btn_wipe": "Borrar todos mis datos…",
        "ask_wipe_title": "Borrar todo",
        "pw_mismatch": "Las contraseñas no coinciden.",
        "lock_title": "Programa bloqueado",
        "lock_wrong": "Contraseña incorrecta.",
        "lock_wait": "Demasiados intentos. Espera {n} s.",
        "btn_unlock": "Desbloquear",
        "btn_quit": "Salir",
        "custom_blocked": "Comando personalizado rechazado: {why}",
        "why_invalid": "formato no válido (debe contener {uri})",
        "why_blocked": "programa no permitido (shell/intérprete)",
        "client_missing_title": "Cliente no encontrado",
        "client_missing": "No encontré “{name}” en este equipo. Instala el cliente (Sober o Mocktail) o elige otro en Ajustes.",
        "err_title": "Algo salió mal",
        "err_generic": "Ocurrió un error inesperado. Los detalles técnicos se guardaron en:\n{path}",
        "root_refuse": "Por seguridad, este programa no debe ejecutarse como administrador (root).",
        "guide_title": "Guía rápida",
        "about_title": "Acerca de",
        "log_panel": "Mensajes",
        "log_ready": "Listo. Añade una cuenta y usa “Abrir para iniciar sesión” la primera vez.",
        "log_cmd": "{name}: {cmd}",
        "log_output": "   salida del cliente en: {path}",
        "log_login_hint": "Inicia sesión dentro del cliente y ciérralo. La sesión queda guardada en este perfil.",
        "log_done": "Se iniciaron todas las cuentas.",
        "log_failed": "{name}: no se pudo iniciar el cliente.",
        "log_profile_deleted": "Perfil borrado: {name}.",
        "err_dir_owner": "La carpeta pertenece a otro usuario: {path}",
        "err_not_file": "La ruta no es un archivo normal.",
        "err_too_big": "Archivo demasiado grande.",
        "err_username": "Usuario no válido (de 3 a 20 caracteres: letras, números y _).",
        "err_password_type": "Contraseña no válida.",
        "err_password_long": "Contraseña demasiado larga (máximo 200 caracteres).",
        "err_password_control": "La contraseña contiene caracteres de control.",
        "err_master_short": "La contraseña maestra debe tener al menos {n} caracteres.",
        "err_vault_content": "Contenido de la bóveda no válido.",
        "err_vault_exists": "Ya existe una bóveda en esta ubicación.",
        "err_vault_version": "Versión de bóveda no compatible.",
        "err_vault_corrupt": "El archivo de la bóveda es ilegible o está dañado.",
        "err_wrong_master": "Contraseña maestra incorrecta.",
        "err_crypto": "Datos cifrados no válidos.",
        "err_not_found": "Cuenta no encontrada.",
        "err_exists": "Ya existe una cuenta llamada {name}.",
        "err_limit": "Se alcanzó el límite de {n} cuentas.",
        "err_import_lines": "El archivo tiene demasiadas líneas (máximo {n}).",
        "err_import_format": "formato esperado: usuario:contraseña",
        "err_import_utf8": "El archivo debe estar en UTF-8.",
        "err_import_read": "No se pudo leer el archivo: {why}",
        "err_write": "No se pudo escribir el archivo: {why}",
        "err_session_path": "Ruta de sesión no válida.",
        "err_symlink": "Se encontró un enlace simbólico dentro de la carpeta de Sober; operación rechazada.",
        "err_account_id": "Identificador de cuenta no válido.",
        "err_session_read": "Error al leer la sesión: {why}",
        "err_profile_outside": "El perfil está fuera de la carpeta de perfiles; operación rechazada.",
        "err_flatpak_missing": "No se encontró flatpak en este equipo.",
        "err_flatpak_query": "Error al consultar flatpak: {why}",
        "err_sober_missing": "Sober no está instalado mediante flatpak.",
        "err_sober_running": "Sober ya está en ejecución. Ciérrelo antes de cambiar de cuenta.",
        "err_custom_denied": "Comando personalizado no permitido.",
        "err_swap_client": "Sin perfiles separados, el cambio de sesión solo funciona con Sober (Flatpak).",
        "err_client_start": "No se pudo iniciar el cliente: {why}",
        "err_deps": "Falta una dependencia. Ejecute: pip install -r requirements.txt",
        "err_attempts": "Se alcanzó el número máximo de intentos.",
        "err_no_accounts": "No hay cuentas registradas.",
        "log_vault_created": "Bóveda creada.",
        "log_vault_unlocked": "Bóveda desbloqueada ({n} cuenta(s)).",
        "log_unlock_fail": "Contraseña maestra incorrecta (intento {n}).",
        "log_locked": "Programa bloqueado.",
        "log_idle_lock": "Bloqueo automático por inactividad.",
        "log_unlocked": "Programa desbloqueado.",
        "log_master_changed": "Contraseña maestra cambiada.",
        "log_migrated": "{n} cuenta(s) de la versión anterior se migraron a la bóveda.",
        "log_added": "Cuenta añadida: {name}.",
        "log_updated": "Cuenta actualizada: {name}.",
        "log_removed": "Cuenta eliminada: {name}.",
        "log_import_read": "Leyendo archivo de importación: {path}",
        "log_import_text": "Leyendo las cuentas pegadas.",
        "log_import_line": "Línea {n} ignorada: {why}",
        "log_import_more": "… y {n} línea(s) no válida(s) más.",
        "log_import_none": "No se encontraron cuentas válidas.",
        "log_import_done": "Importación terminada: {added} nueva(s), {updated} actualizada(s), {skipped} conservada(s), {duplicated} repetida(s) en el archivo, {invalid} línea(s) no válida(s).",
        "log_export_done": "{n} cuenta(s) exportada(s) a: {path}",
        "log_export_warn": "El archivo exportado contiene contraseñas en texto plano. Bórrelo después de usarlo.",
        "log_pw_shown": "Contraseña de {name} mostrada en pantalla.",
        "log_pw_copied": "Contraseña de {name} copiada; se borrará del portapapeles en {n} s.",
        "log_clip_cleared": "Portapapeles borrado.",
        "log_launch": "Abriendo el cliente con la cuenta: {name}",
        "log_client_exit": "{name}: el cliente se cerró justo después de abrir (código {code}). Vea {path}",
        "log_session_prev": "Sesión actual guardada en la cuenta: {name}",
        "log_session_backup": "Sesión anterior sin cuenta guardada como copia cifrada.",
        "log_session_restored": "Sesión restaurada para la cuenta: {name}",
        "log_session_missing": "La cuenta {name} aún no tiene sesión guardada; inicie sesión en Sober.",
        "log_session_saved": "Sesión guardada para la cuenta: {name}",
        "log_session_none": "No se encontró ninguna sesión de Sober para guardar.",
        "log_session_isolated": "Con perfiles separados cada cuenta ya guarda su propia sesión; esta acción solo se aplica sin perfiles separados.",
        "log_settings_corrupt": "El archivo de configuración estaba dañado; se guardó como .corrupt y se restauraron los valores predeterminados.",
        "log_settings_saved": "Configuración guardada.",
        "log_exit": "Saliendo.",
        "log_interrupted": "Interrumpido.",
        "log_unhandled": "Error inesperado. Detalles en: {path}",
        "log_count": "{n} cuenta(s) registrada(s).",
        "col_user": "Usuario",
        "col_password": "Contraseña",
        "btn_copy": "Copiar contraseña",
        "act_copy": "Copiar contraseña",
        "act_show": "Mostrar contraseña…",
        "act_import": "Importar cuentas desde un archivo…",
        "act_import_text": "Importar cuentas pegando texto…",
        "act_export": "Exportar cuentas…",
        "act_save_session": "Guardar la sesión actual de Sober en la cuenta activa",
        "ph_search": "Buscar por usuario, grupo o nota",
        "ph_keep_pw": "Déjelo en blanco para mantener la contraseña actual",
        "chk_clear_pw": "Eliminar la contraseña guardada",
        "chk_show_pw": "Mostrar lo que escribo",
        "hint_add": "La contraseña es opcional y se guarda cifrada en la bóveda. Para entrar en la cuenta, use “Abrir para iniciar sesión” una vez e inicie sesión dentro del cliente.",
        "warn_title": "Aviso",
        "warn_user_title": "Usuario no válido",
        "warn_nopw_title": "Sin contraseña",
        "warn_nopw": "Esta cuenta no tiene contraseña guardada.",
        "warn_swap_one": "Sin perfiles separados solo se puede usar una cuenta a la vez.",
        "dlg_create_title": "Crear bóveda",
        "create_prompt": "Cree la contraseña maestra. Protege todas las contraseñas y sesiones guardadas y no se puede recuperar si se olvida.",
        "lbl_master": "Contraseña maestra",
        "lbl_master_repeat": "Repita la contraseña maestra",
        "chk_isolate": "Perfil separado por cuenta (recomendado; permite varias cuentas abiertas a la vez)",
        "sec_privacy": "Privacidad: este programa no usa internet ni envía datos. Las contraseñas se guardan cifradas en la bóveda (contraseña maestra) y todas las carpetas del programa son privadas (solo usted accede).",
        "hint_lock": "El bloqueo oculta la ventana hasta que se introduzca la contraseña maestra. Los inicios de sesión de los perfiles separados están en las carpetas del propio cliente y este programa no los cifra; use cifrado de disco para protegerlos.",
        "btn_changemaster": "Cambiar contraseña maestra…",
        "ask_wipe": "Esto borra la bóveda con todas las cuentas y contraseñas, los perfiles e inicios de sesión guardados, las sesiones, los registros y la configuración. No se puede deshacer. ¿Continuar?",
        "info_wipe_done": "Se borraron todos los datos del programa. El programa se cerrará.",
        "pw_current": "Introduzca la contraseña maestra:",
        "pw_confirm": "Confirme la contraseña maestra:",
        "pw_title": "Contraseña maestra",
        "pw_new": "Nueva contraseña maestra (mínimo 8 caracteres):",
        "pw_repeat": "Repita la nueva contraseña maestra:",
        "lock_prompt": "Introduzca la contraseña maestra para continuar:",
        "dlg_secret_title": "Contraseña de {name}",
        "pw_none": "(sin contraseña guardada)",
        "import_title": "Importar cuentas",
        "import_filter": "Archivos de texto (*.txt);;Todos los archivos (*)",
        "import_text_hint": "Pegue una cuenta por línea, con el formato usuario:contraseña.",
        "ask_overwrite_title": "Cuentas existentes",
        "ask_overwrite": "{n} cuenta(s) ya existen en la bóveda. ¿Reemplazar su contraseña por la importada?",
        "export_title": "Exportar cuentas",
        "ask_export": "El archivo exportado contendrá todas las contraseñas en texto plano. ¿Continuar?",
        "guide_text": "1. En Añadir, indique el usuario (y la contraseña, si quiere guardarla).\n2. Para traer varias cuentas a la vez, use Archivo > Importar, con una cuenta por línea en el formato usuario:contraseña. El mismo formato sirve para exportar.\n3. Seleccione la cuenta y haga clic en “Abrir para iniciar sesión”. Inicie sesión dentro del cliente (Sober o Mocktail) y ciérrelo. Se hace una vez por cuenta.\n4. Escriba el ID del juego (el número de la URL de la página del juego en roblox.com), seleccione las cuentas y haga clic en “Entrar con las seleccionadas”.\n5. Para pegar la contraseña al iniciar sesión, use “Copiar contraseña”: se borra del portapapeles tras {n} segundos.\n\nAtajos: Ctrl+N añadir, Ctrl+E editar, Supr eliminar, Ctrl+Shift+C copiar contraseña, Ctrl+I importar, Ctrl+Shift+E exportar, Ctrl+Intro entrar al juego, Ctrl+L bloquear, Ctrl+, configuración, F1 esta guía.\n\nTodo lo que ocurre también aparece en el terminal y en el archivo de registro. Las contraseñas nunca se registran.",
        "about_text": "Gestor de cuentas de Roblox {version}\nProyecto independiente, sin vínculo con Roblox Corporation.\nNo usa internet ni envía datos.",
        "cli_desc": "Gestor de cuentas de Roblox para Linux. Sin comando, abre la interfaz gráfica.",
        "cli_list": "lista las cuentas",
        "cli_add": "añade una cuenta",
        "cli_remove": "elimina una cuenta",
        "cli_import": "importa cuentas de un archivo usuario:contraseña",
        "cli_export": "exporta las cuentas a un archivo usuario:contraseña",
        "cli_launch": "abre el cliente con una cuenta",
        "cli_version": "muestra la versión",
        "cli_yes": "no pide confirmación",
        "cli_overwrite": "reemplaza la contraseña de las cuentas que ya existen",
        "cli_force": "sobrescribe el archivo de destino si existe",
        "cli_account": "usuario de la cuenta",
        "cli_file": "ruta del archivo",
        "cli_prompt_master": "Contraseña maestra: ",
        "cli_prompt_confirm": "Confirme la contraseña maestra: ",
        "cli_prompt_new": "Cree la contraseña maestra: ",
        "cli_prompt_repeat": "Repita la contraseña maestra: ",
        "cli_prompt_pass": "Contraseña (vacío para ninguna): ",
        "cli_confirm_remove": "¿Eliminar {name}? [s/N]: ",
        "cli_confirm_replace": "{path} ya existe. ¿Reemplazarlo? [s/N]: ",
        "cli_confirm_overwrite": "{n} cuenta(s) ya existen. ¿Reemplazar las contraseñas? [s/N]: ",
    },
    "fr": {
        "app_title": "Gestionnaire de comptes Roblox",
        "menu_file": "&Fichier",
        "menu_help": "&Aide",
        "act_add": "Ajouter un compte",
        "act_edit": "Modifier le compte",
        "act_remove": "Supprimer le compte",
        "act_login": "Ouvrir pour se connecter",
        "act_launch": "Rejoindre le jeu avec les comptes sélectionnés",
        "act_lock": "Verrouiller",
        "act_settings": "Paramètres",
        "act_quit": "Quitter",
        "act_guide": "Guide rapide",
        "act_about": "À propos",
        "col_group": "Groupe",
        "col_last": "Dernière connexion",
        "col_notes": "Notes",
        "btn_add": "Ajouter",
        "btn_edit": "Modifier",
        "btn_remove": "Supprimer",
        "btn_login": "Ouvrir pour se connecter",
        "btn_settings": "Paramètres",
        "btn_launch": "Rejoindre avec la sélection",
        "btn_lock": "Verrouiller",
        "ph_place": "ID du jeu (placeId)",
        "ph_job": "ID du serveur (facultatif)",
        "delay_suffix": " s entre les comptes",
        "accounts_list": "Liste des comptes",
        "never": "—",
        "dlg_add": "Ajouter un compte",
        "dlg_edit": "Modifier le compte",
        "lbl_group": "Groupe",
        "lbl_notes": "Notes",
        "warn_noacc_title": "Aucun compte",
        "warn_noacc": "Sélectionnez au moins un compte dans la liste.",
        "warn_game_title": "Données invalides",
        "warn_game": "L’ID du jeu ne doit contenir que des chiffres (19 au maximum).",
        "warn_job": "L’ID du serveur doit avoir le format 00000000-0000-0000-0000-000000000000.",
        "warn_many_title": "Trop de comptes",
        "warn_many": "La limite par lot est de {n} comptes. Modifiez-la dans Paramètres > Sécurité.",
        "ask_many_title": "Confirmer",
        "ask_many": "Ouvrir le client pour {n} comptes maintenant ?",
        "ask_remove_title": "Supprimer",
        "ask_remove": "Supprimer {n} compte(s) de la liste ?",
        "chk_delete_profile": "Supprimer aussi la connexion enregistrée (profil) de ces comptes",
        "settings_title": "Paramètres",
        "tab_general": "Général",
        "tab_security": "Sécurité",
        "tab_access": "Accessibilité et langue",
        "lbl_client": "Client",
        "lbl_command": "Commande",
        "hint_command": "Utilisez {uri} à l’endroit où va le lien du jeu. Modifiable seulement avec « Personnalisé », après avoir autorisé les commandes personnalisées dans l’onglet Sécurité.",
        "lbl_language": "Langue",
        "lang_auto": "Automatique (langue du système)",
        "lbl_font": "Taille du texte",
        "font_small": "Petite",
        "font_normal": "Normale",
        "font_large": "Grande",
        "font_xlarge": "Très grande",
        "lbl_theme": "Apparence",
        "theme_system": "Par défaut du système",
        "theme_light": "Clair",
        "theme_dark": "Sombre",
        "theme_hc_dark": "Contraste élevé (sombre)",
        "theme_hc_light": "Contraste élevé (clair)",
        "chk_custom": "Autoriser une commande personnalisée (avancé)",
        "hint_custom": "Attention : une commande personnalisée s’exécute avec vos droits. N’utilisez que des commandes que vous connaissez.",
        "lbl_maxbatch": "Nombre maximal de comptes à la fois",
        "lbl_idle": "Verrouiller après inactivité",
        "idle_suffix": " min",
        "idle_off": "Jamais",
        "btn_wipe": "Effacer toutes mes données…",
        "ask_wipe_title": "Tout effacer",
        "pw_mismatch": "Les mots de passe ne correspondent pas.",
        "lock_title": "Programme verrouillé",
        "lock_wrong": "Mot de passe incorrect.",
        "lock_wait": "Trop de tentatives. Patientez {n} s.",
        "btn_unlock": "Déverrouiller",
        "btn_quit": "Quitter",
        "custom_blocked": "Commande personnalisée refusée : {why}",
        "why_invalid": "format invalide (doit contenir {uri})",
        "why_blocked": "programme non autorisé (shell/interpréteur)",
        "client_missing_title": "Client introuvable",
        "client_missing": "Je n’ai pas trouvé « {name} » sur cet ordinateur. Installez le client (Sober ou Mocktail) ou choisissez-en un autre dans Paramètres.",
        "err_title": "Un problème est survenu",
        "err_generic": "Une erreur inattendue s’est produite. Les détails techniques ont été enregistrés dans :\n{path}",
        "root_refuse": "Par sécurité, ce programme ne doit pas être exécuté en administrateur (root).",
        "guide_title": "Guide rapide",
        "about_title": "À propos",
        "log_panel": "Messages",
        "log_ready": "Prêt. Ajoutez un compte et utilisez « Ouvrir pour se connecter » la première fois.",
        "log_cmd": "{name} : {cmd}",
        "log_output": "   sortie du client dans : {path}",
        "log_login_hint": "Connectez-vous dans le client puis fermez-le. La connexion reste enregistrée dans ce profil.",
        "log_done": "Tous les comptes ont été lancés.",
        "log_failed": "{name} : impossible de lancer le client.",
        "log_profile_deleted": "Profil supprimé : {name}.",
        "err_dir_owner": "Le dossier appartient à un autre utilisateur : {path}",
        "err_not_file": "Le chemin n'est pas un fichier ordinaire.",
        "err_too_big": "Fichier trop volumineux.",
        "err_username": "Nom d'utilisateur invalide (3 à 20 caractères : lettres, chiffres et _).",
        "err_password_type": "Mot de passe invalide.",
        "err_password_long": "Mot de passe trop long (200 caractères au maximum).",
        "err_password_control": "Le mot de passe contient des caractères de contrôle.",
        "err_master_short": "Le mot de passe principal doit contenir au moins {n} caractères.",
        "err_vault_content": "Contenu du coffre invalide.",
        "err_vault_exists": "Un coffre existe déjà à cet emplacement.",
        "err_vault_version": "Version de coffre non prise en charge.",
        "err_vault_corrupt": "Le fichier du coffre est illisible ou corrompu.",
        "err_wrong_master": "Mot de passe principal incorrect.",
        "err_crypto": "Données chiffrées invalides.",
        "err_not_found": "Compte introuvable.",
        "err_exists": "Un compte nommé {name} existe déjà.",
        "err_limit": "Limite de {n} comptes atteinte.",
        "err_import_lines": "Le fichier a trop de lignes ({n} au maximum).",
        "err_import_format": "format attendu : utilisateur:mot_de_passe",
        "err_import_utf8": "Le fichier doit être encodé en UTF-8.",
        "err_import_read": "Impossible de lire le fichier : {why}",
        "err_write": "Impossible d'écrire le fichier : {why}",
        "err_session_path": "Chemin de session invalide.",
        "err_symlink": "Un lien symbolique a été trouvé dans le dossier de Sober ; opération refusée.",
        "err_account_id": "Identifiant de compte invalide.",
        "err_session_read": "Échec de lecture de la session : {why}",
        "err_profile_outside": "Le profil est en dehors du dossier des profils ; opération refusée.",
        "err_flatpak_missing": "flatpak est introuvable sur cet ordinateur.",
        "err_flatpak_query": "Échec de l'interrogation de flatpak : {why}",
        "err_sober_missing": "Sober n'est pas installé via flatpak.",
        "err_sober_running": "Sober est déjà en cours d'exécution. Fermez-le avant de changer de compte.",
        "err_custom_denied": "Commande personnalisée non autorisée.",
        "err_swap_client": "Sans profils séparés, le changement de session ne fonctionne qu'avec Sober (Flatpak).",
        "err_client_start": "Impossible de démarrer le client : {why}",
        "err_deps": "Dépendance manquante. Lancez : pip install -r requirements.txt",
        "err_attempts": "Nombre maximal de tentatives atteint.",
        "err_no_accounts": "Aucun compte enregistré.",
        "log_vault_created": "Coffre créé.",
        "log_vault_unlocked": "Coffre déverrouillé ({n} compte(s)).",
        "log_unlock_fail": "Mot de passe principal incorrect (tentative {n}).",
        "log_locked": "Application verrouillée.",
        "log_idle_lock": "Verrouillage automatique après inactivité.",
        "log_unlocked": "Application déverrouillée.",
        "log_master_changed": "Mot de passe principal modifié.",
        "log_migrated": "{n} compte(s) de la version précédente ont été migrés vers le coffre.",
        "log_added": "Compte ajouté : {name}.",
        "log_updated": "Compte mis à jour : {name}.",
        "log_removed": "Compte supprimé : {name}.",
        "log_import_read": "Lecture du fichier d'importation : {path}",
        "log_import_text": "Lecture des comptes collés.",
        "log_import_line": "Ligne {n} ignorée : {why}",
        "log_import_more": "… et {n} autre(s) ligne(s) invalide(s).",
        "log_import_none": "Aucun compte valide trouvé.",
        "log_import_done": "Importation terminée : {added} nouveau(x), {updated} mis à jour, {skipped} conservé(s), {duplicated} en double dans le fichier, {invalid} ligne(s) invalide(s).",
        "log_export_done": "{n} compte(s) exporté(s) vers : {path}",
        "log_export_warn": "Le fichier exporté contient des mots de passe en clair. Supprimez-le après usage.",
        "log_pw_shown": "Mot de passe de {name} affiché à l'écran.",
        "log_pw_copied": "Mot de passe de {name} copié ; il sera effacé du presse-papiers dans {n} s.",
        "log_clip_cleared": "Presse-papiers vidé.",
        "log_launch": "Ouverture du client avec le compte : {name}",
        "log_client_exit": "{name} : le client s'est arrêté juste après le démarrage (code {code}). Voir {path}",
        "log_session_prev": "Session actuelle enregistrée pour le compte : {name}",
        "log_session_backup": "Session précédente sans compte enregistrée comme sauvegarde chiffrée.",
        "log_session_restored": "Session restaurée pour le compte : {name}",
        "log_session_missing": "Le compte {name} n'a pas encore de session enregistrée ; connectez-vous dans Sober.",
        "log_session_saved": "Session enregistrée pour le compte : {name}",
        "log_session_none": "Aucune session Sober à enregistrer.",
        "log_session_isolated": "Avec des profils séparés, chaque compte garde déjà sa propre session ; cette action ne s'applique que sans profils séparés.",
        "log_settings_corrupt": "Le fichier de paramètres était corrompu ; il a été conservé en .corrupt et les valeurs par défaut ont été rétablies.",
        "log_settings_saved": "Paramètres enregistrés.",
        "log_exit": "Fermeture.",
        "log_interrupted": "Interrompu.",
        "log_unhandled": "Erreur inattendue. Détails dans : {path}",
        "log_count": "{n} compte(s) enregistré(s).",
        "col_user": "Utilisateur",
        "col_password": "Mot de passe",
        "btn_copy": "Copier le mot de passe",
        "act_copy": "Copier le mot de passe",
        "act_show": "Afficher le mot de passe…",
        "act_import": "Importer des comptes depuis un fichier…",
        "act_import_text": "Importer des comptes en collant du texte…",
        "act_export": "Exporter les comptes…",
        "act_save_session": "Enregistrer la session Sober actuelle dans le compte actif",
        "ph_search": "Rechercher par utilisateur, groupe ou note",
        "ph_keep_pw": "Laissez vide pour conserver le mot de passe actuel",
        "chk_clear_pw": "Supprimer le mot de passe enregistré",
        "chk_show_pw": "Afficher ce que je tape",
        "hint_add": "Le mot de passe est facultatif et reste chiffré dans le coffre. Pour accéder au compte, utilisez « Ouvrir pour se connecter » une fois et connectez-vous dans le client.",
        "warn_title": "Attention",
        "warn_user_title": "Nom d'utilisateur invalide",
        "warn_nopw_title": "Pas de mot de passe",
        "warn_nopw": "Ce compte n'a pas de mot de passe enregistré.",
        "warn_swap_one": "Sans profils séparés, un seul compte peut être utilisé à la fois.",
        "dlg_create_title": "Créer le coffre",
        "create_prompt": "Créez le mot de passe principal. Il protège tous les mots de passe et sessions enregistrés et ne peut pas être récupéré en cas d'oubli.",
        "lbl_master": "Mot de passe principal",
        "lbl_master_repeat": "Répétez le mot de passe principal",
        "chk_isolate": "Profil séparé par compte (recommandé ; permet d'ouvrir plusieurs comptes en même temps)",
        "sec_privacy": "Confidentialité : ce programme n'utilise pas internet et n'envoie aucune donnée. Les mots de passe sont chiffrés dans le coffre (mot de passe principal) et tous les dossiers du programme sont privés (vous seul y avez accès).",
        "hint_lock": "Le verrouillage masque la fenêtre jusqu'à la saisie du mot de passe principal. Les connexions des profils séparés se trouvent dans les dossiers du client lui-même et ne sont pas chiffrées par ce programme ; utilisez le chiffrement du disque pour les protéger.",
        "btn_changemaster": "Changer le mot de passe principal…",
        "ask_wipe": "Cela supprime le coffre avec tous les comptes et mots de passe, les profils et connexions enregistrés, les sessions, les journaux et les paramètres. Cette action est irréversible. Continuer ?",
        "info_wipe_done": "Toutes les données du programme ont été supprimées. Le programme va se fermer.",
        "pw_current": "Saisissez le mot de passe principal :",
        "pw_confirm": "Confirmez le mot de passe principal :",
        "pw_title": "Mot de passe principal",
        "pw_new": "Nouveau mot de passe principal (8 caractères minimum) :",
        "pw_repeat": "Répétez le nouveau mot de passe principal :",
        "lock_prompt": "Saisissez le mot de passe principal pour continuer :",
        "dlg_secret_title": "Mot de passe de {name}",
        "pw_none": "(aucun mot de passe enregistré)",
        "import_title": "Importer des comptes",
        "import_filter": "Fichiers texte (*.txt);;Tous les fichiers (*)",
        "import_text_hint": "Collez un compte par ligne, au format utilisateur:mot_de_passe.",
        "ask_overwrite_title": "Comptes existants",
        "ask_overwrite": "{n} compte(s) existent déjà dans le coffre. Remplacer leur mot de passe par celui importé ?",
        "export_title": "Exporter les comptes",
        "ask_export": "Le fichier exporté contiendra tous les mots de passe en clair. Continuer ?",
        "guide_text": "1. Dans Ajouter, saisissez l'utilisateur (et le mot de passe, si vous voulez le conserver).\n2. Pour importer plusieurs comptes d'un coup, utilisez Fichier > Importer, avec un compte par ligne au format utilisateur:mot_de_passe. Le même format sert à l'exportation.\n3. Sélectionnez le compte et cliquez sur « Ouvrir pour se connecter ». Connectez-vous dans le client (Sober ou Mocktail) puis fermez-le. Cela se fait une fois par compte.\n4. Saisissez l'ID du jeu (le nombre dans l'URL de la page du jeu sur roblox.com), sélectionnez les comptes et cliquez sur « Rejoindre avec la sélection ».\n5. Pour coller le mot de passe à la connexion, utilisez « Copier le mot de passe » : il est effacé du presse-papiers après {n} secondes.\n\nRaccourcis : Ctrl+N ajouter, Ctrl+E modifier, Suppr supprimer, Ctrl+Maj+C copier le mot de passe, Ctrl+I importer, Ctrl+Maj+E exporter, Ctrl+Entrée rejoindre le jeu, Ctrl+L verrouiller, Ctrl+, paramètres, F1 ce guide.\n\nTout ce qui se passe apparaît aussi dans le terminal et dans le fichier journal. Les mots de passe ne sont jamais enregistrés.",
        "about_text": "Gestionnaire de comptes Roblox {version}\nProjet indépendant, sans lien avec Roblox Corporation.\nN'utilise pas internet et n'envoie aucune donnée.",
        "cli_desc": "Gestionnaire de comptes Roblox pour Linux. Sans commande, ouvre l'interface graphique.",
        "cli_list": "liste les comptes",
        "cli_add": "ajoute un compte",
        "cli_remove": "supprime un compte",
        "cli_import": "importe des comptes depuis un fichier utilisateur:mot_de_passe",
        "cli_export": "exporte les comptes vers un fichier utilisateur:mot_de_passe",
        "cli_launch": "ouvre le client avec un compte",
        "cli_version": "affiche la version",
        "cli_yes": "ne demande pas de confirmation",
        "cli_overwrite": "remplace le mot de passe des comptes déjà existants",
        "cli_force": "écrase le fichier de destination s'il existe",
        "cli_account": "nom d'utilisateur du compte",
        "cli_file": "chemin du fichier",
        "cli_prompt_master": "Mot de passe principal : ",
        "cli_prompt_confirm": "Confirmez le mot de passe principal : ",
        "cli_prompt_new": "Créez le mot de passe principal : ",
        "cli_prompt_repeat": "Répétez le mot de passe principal : ",
        "cli_prompt_pass": "Mot de passe (vide pour aucun) : ",
        "cli_confirm_remove": "Supprimer {name} ? [o/N] : ",
        "cli_confirm_replace": "{path} existe déjà. Le remplacer ? [o/N] : ",
        "cli_confirm_overwrite": "{n} compte(s) existent déjà. Remplacer les mots de passe ? [o/N] : ",
    },
    "de": {
        "app_title": "Roblox-Kontoverwaltung",
        "menu_file": "&Datei",
        "menu_help": "&Hilfe",
        "act_add": "Konto hinzufügen",
        "act_edit": "Konto bearbeiten",
        "act_remove": "Konto entfernen",
        "act_login": "Zum Anmelden öffnen",
        "act_launch": "Mit den ausgewählten Konten beitreten",
        "act_lock": "Sperren",
        "act_settings": "Einstellungen",
        "act_quit": "Beenden",
        "act_guide": "Kurzanleitung",
        "act_about": "Über",
        "col_group": "Gruppe",
        "col_last": "Zuletzt beigetreten",
        "col_notes": "Notizen",
        "btn_add": "Hinzufügen",
        "btn_edit": "Bearbeiten",
        "btn_remove": "Entfernen",
        "btn_login": "Zum Anmelden öffnen",
        "btn_settings": "Einstellungen",
        "btn_launch": "Mit Auswahl beitreten",
        "btn_lock": "Sperren",
        "ph_place": "Spiel-ID (placeId)",
        "ph_job": "Server-ID (optional)",
        "delay_suffix": " s zwischen Konten",
        "accounts_list": "Kontenliste",
        "never": "—",
        "dlg_add": "Konto hinzufügen",
        "dlg_edit": "Konto bearbeiten",
        "lbl_group": "Gruppe",
        "lbl_notes": "Notizen",
        "warn_noacc_title": "Kein Konto",
        "warn_noacc": "Wählen Sie mindestens ein Konto in der Liste aus.",
        "warn_game_title": "Ungültige Eingabe",
        "warn_game": "Die Spiel-ID darf nur Ziffern enthalten (höchstens 19).",
        "warn_job": "Die Server-ID muss das Format 00000000-0000-0000-0000-000000000000 haben.",
        "warn_many_title": "Zu viele Konten",
        "warn_many": "Das Limit pro Durchgang beträgt {n} Konten. Ändern unter Einstellungen > Sicherheit.",
        "ask_many_title": "Bestätigen",
        "ask_many": "Den Client jetzt für {n} Konten öffnen?",
        "ask_remove_title": "Entfernen",
        "ask_remove": "{n} Konto/Konten aus der Liste entfernen?",
        "chk_delete_profile": "Auch die gespeicherte Anmeldung (Profil) dieser Konten löschen",
        "settings_title": "Einstellungen",
        "tab_general": "Allgemein",
        "tab_security": "Sicherheit",
        "tab_access": "Barrierefreiheit und Sprache",
        "lbl_client": "Client",
        "lbl_command": "Befehl",
        "hint_command": "Verwenden Sie {uri} an der Stelle des Spiel-Links. Nur bei „Benutzerdefiniert“ bearbeitbar, nachdem benutzerdefinierte Befehle im Reiter Sicherheit erlaubt wurden.",
        "lbl_language": "Sprache",
        "lang_auto": "Automatisch (Systemsprache)",
        "lbl_font": "Textgröße",
        "font_small": "Klein",
        "font_normal": "Normal",
        "font_large": "Groß",
        "font_xlarge": "Sehr groß",
        "lbl_theme": "Darstellung",
        "theme_system": "Systemstandard",
        "theme_light": "Hell",
        "theme_dark": "Dunkel",
        "theme_hc_dark": "Hoher Kontrast (dunkel)",
        "theme_hc_light": "Hoher Kontrast (hell)",
        "chk_custom": "Benutzerdefinierten Befehl erlauben (fortgeschritten)",
        "hint_custom": "Achtung: Ein benutzerdefinierter Befehl läuft mit Ihren Rechten. Verwenden Sie nur Befehle, die Sie kennen.",
        "lbl_maxbatch": "Maximale Kontenzahl gleichzeitig",
        "lbl_idle": "Nach Inaktivität sperren",
        "idle_suffix": " Min.",
        "idle_off": "Nie",
        "btn_wipe": "Alle meine Daten löschen…",
        "ask_wipe_title": "Alles löschen",
        "pw_mismatch": "Die Passwörter stimmen nicht überein.",
        "lock_title": "Programm gesperrt",
        "lock_wrong": "Falsches Passwort.",
        "lock_wait": "Zu viele Versuche. Bitte {n} s warten.",
        "btn_unlock": "Entsperren",
        "btn_quit": "Beenden",
        "custom_blocked": "Benutzerdefinierter Befehl abgelehnt: {why}",
        "why_invalid": "ungültiges Format (muss {uri} enthalten)",
        "why_blocked": "Programm nicht erlaubt (Shell/Interpreter)",
        "client_missing_title": "Client nicht gefunden",
        "client_missing": "„{name}“ wurde auf diesem Computer nicht gefunden. Installieren Sie den Client (Sober oder Mocktail) oder wählen Sie in den Einstellungen einen anderen.",
        "err_title": "Etwas ist schiefgelaufen",
        "err_generic": "Ein unerwarteter Fehler ist aufgetreten. Technische Details wurden gespeichert unter:\n{path}",
        "root_refuse": "Aus Sicherheitsgründen sollte dieses Programm nicht als Administrator (root) ausgeführt werden.",
        "guide_title": "Kurzanleitung",
        "about_title": "Über",
        "log_panel": "Meldungen",
        "log_ready": "Bereit. Fügen Sie ein Konto hinzu und nutzen Sie beim ersten Mal „Zum Anmelden öffnen“.",
        "log_cmd": "{name}: {cmd}",
        "log_output": "   Client-Ausgabe in: {path}",
        "log_login_hint": "Melden Sie sich im Client an und schließen Sie ihn. Die Anmeldung bleibt in diesem Profil gespeichert.",
        "log_done": "Alle Konten wurden gestartet.",
        "log_failed": "{name}: Der Client konnte nicht gestartet werden.",
        "log_profile_deleted": "Profil gelöscht: {name}.",
        "err_dir_owner": "Der Ordner gehört einem anderen Benutzer: {path}",
        "err_not_file": "Der Pfad ist keine reguläre Datei.",
        "err_too_big": "Datei zu groß.",
        "err_username": "Ungültiger Benutzername (3 bis 20 Zeichen: Buchstaben, Ziffern und _).",
        "err_password_type": "Ungültiges Passwort.",
        "err_password_long": "Passwort zu lang (höchstens 200 Zeichen).",
        "err_password_control": "Das Passwort enthält Steuerzeichen.",
        "err_master_short": "Das Master-Passwort muss mindestens {n} Zeichen lang sein.",
        "err_vault_content": "Ungültiger Tresorinhalt.",
        "err_vault_exists": "An diesem Ort existiert bereits ein Tresor.",
        "err_vault_version": "Nicht unterstützte Tresorversion.",
        "err_vault_corrupt": "Die Tresordatei ist nicht lesbar oder beschädigt.",
        "err_wrong_master": "Falsches Master-Passwort.",
        "err_crypto": "Ungültige verschlüsselte Daten.",
        "err_not_found": "Konto nicht gefunden.",
        "err_exists": "Ein Konto namens {name} existiert bereits.",
        "err_limit": "Limit von {n} Konten erreicht.",
        "err_import_lines": "Die Datei hat zu viele Zeilen (höchstens {n}).",
        "err_import_format": "erwartetes Format: Benutzer:Passwort",
        "err_import_utf8": "Die Datei muss UTF-8-kodiert sein.",
        "err_import_read": "Die Datei konnte nicht gelesen werden: {why}",
        "err_write": "Die Datei konnte nicht geschrieben werden: {why}",
        "err_session_path": "Ungültiger Sitzungspfad.",
        "err_symlink": "Im Sober-Ordner wurde ein symbolischer Link gefunden; Vorgang abgelehnt.",
        "err_account_id": "Ungültige Konto-Kennung.",
        "err_session_read": "Sitzung konnte nicht gelesen werden: {why}",
        "err_profile_outside": "Das Profil liegt außerhalb des Profilordners; Vorgang abgelehnt.",
        "err_flatpak_missing": "flatpak wurde auf diesem Computer nicht gefunden.",
        "err_flatpak_query": "flatpak-Abfrage fehlgeschlagen: {why}",
        "err_sober_missing": "Sober ist nicht über flatpak installiert.",
        "err_sober_running": "Sober läuft bereits. Schließen Sie es, bevor Sie das Konto wechseln.",
        "err_custom_denied": "Benutzerdefinierter Befehl nicht erlaubt.",
        "err_swap_client": "Ohne getrennte Profile funktioniert der Sitzungswechsel nur mit Sober (Flatpak).",
        "err_client_start": "Der Client konnte nicht gestartet werden: {why}",
        "err_deps": "Fehlende Abhängigkeit. Führen Sie aus: pip install -r requirements.txt",
        "err_attempts": "Maximale Anzahl an Versuchen erreicht.",
        "err_no_accounts": "Keine Konten vorhanden.",
        "log_vault_created": "Tresor erstellt.",
        "log_vault_unlocked": "Tresor entsperrt ({n} Konto/Konten).",
        "log_unlock_fail": "Falsches Master-Passwort (Versuch {n}).",
        "log_locked": "Programm gesperrt.",
        "log_idle_lock": "Automatisch wegen Inaktivität gesperrt.",
        "log_unlocked": "Programm entsperrt.",
        "log_master_changed": "Master-Passwort geändert.",
        "log_migrated": "{n} Konto/Konten der Vorgängerversion wurden in den Tresor übernommen.",
        "log_added": "Konto hinzugefügt: {name}.",
        "log_updated": "Konto aktualisiert: {name}.",
        "log_removed": "Konto entfernt: {name}.",
        "log_import_read": "Importdatei wird gelesen: {path}",
        "log_import_text": "Eingefügte Konten werden gelesen.",
        "log_import_line": "Zeile {n} übersprungen: {why}",
        "log_import_more": "… und {n} weitere ungültige Zeile(n).",
        "log_import_none": "Keine gültigen Konten gefunden.",
        "log_import_done": "Import abgeschlossen: {added} neu, {updated} aktualisiert, {skipped} behalten, {duplicated} doppelt in der Datei, {invalid} ungültige Zeile(n).",
        "log_export_done": "{n} Konto/Konten exportiert nach: {path}",
        "log_export_warn": "Die exportierte Datei enthält Passwörter im Klartext. Löschen Sie sie nach der Verwendung.",
        "log_pw_shown": "Passwort von {name} auf dem Bildschirm angezeigt.",
        "log_pw_copied": "Passwort von {name} kopiert; es wird in {n} s aus der Zwischenablage gelöscht.",
        "log_clip_cleared": "Zwischenablage geleert.",
        "log_launch": "Client wird mit dem Konto geöffnet: {name}",
        "log_client_exit": "{name}: Der Client wurde direkt nach dem Start beendet (Code {code}). Siehe {path}",
        "log_session_prev": "Aktuelle Sitzung für das Konto gespeichert: {name}",
        "log_session_backup": "Vorherige Sitzung ohne Konto als verschlüsselte Sicherung gespeichert.",
        "log_session_restored": "Sitzung für das Konto wiederhergestellt: {name}",
        "log_session_missing": "Für das Konto {name} ist noch keine Sitzung gespeichert; melden Sie sich in Sober an.",
        "log_session_saved": "Sitzung für das Konto gespeichert: {name}",
        "log_session_none": "Keine Sober-Sitzung zum Speichern gefunden.",
        "log_session_isolated": "Bei getrennten Profilen behält jedes Konto seine eigene Sitzung; diese Aktion gilt nur ohne getrennte Profile.",
        "log_settings_corrupt": "Die Einstellungsdatei war beschädigt; sie wurde als .corrupt aufbewahrt und die Standardwerte wurden wiederhergestellt.",
        "log_settings_saved": "Einstellungen gespeichert.",
        "log_exit": "Wird beendet.",
        "log_interrupted": "Unterbrochen.",
        "log_unhandled": "Unerwarteter Fehler. Details in: {path}",
        "log_count": "{n} Konto/Konten vorhanden.",
        "col_user": "Benutzername",
        "col_password": "Passwort",
        "btn_copy": "Passwort kopieren",
        "act_copy": "Passwort kopieren",
        "act_show": "Passwort anzeigen…",
        "act_import": "Konten aus einer Datei importieren…",
        "act_import_text": "Konten durch Einfügen von Text importieren…",
        "act_export": "Konten exportieren…",
        "act_save_session": "Aktuelle Sober-Sitzung im aktiven Konto speichern",
        "ph_search": "Nach Benutzer, Gruppe oder Notiz suchen",
        "ph_keep_pw": "Leer lassen, um das aktuelle Passwort zu behalten",
        "chk_clear_pw": "Gespeichertes Passwort entfernen",
        "chk_show_pw": "Eingabe anzeigen",
        "hint_add": "Das Passwort ist optional und wird verschlüsselt im Tresor gespeichert. Um sich beim Konto anzumelden, verwenden Sie einmal „Zum Anmelden öffnen“ und melden Sie sich im Client an.",
        "warn_title": "Hinweis",
        "warn_user_title": "Ungültiger Benutzername",
        "warn_nopw_title": "Kein Passwort",
        "warn_nopw": "Für dieses Konto ist kein Passwort gespeichert.",
        "warn_swap_one": "Ohne getrennte Profile kann nur ein Konto gleichzeitig verwendet werden.",
        "dlg_create_title": "Tresor erstellen",
        "create_prompt": "Legen Sie das Master-Passwort fest. Es schützt alle gespeicherten Passwörter und Sitzungen und kann bei Verlust nicht wiederhergestellt werden.",
        "lbl_master": "Master-Passwort",
        "lbl_master_repeat": "Master-Passwort wiederholen",
        "chk_isolate": "Eigenes Profil pro Konto (empfohlen; erlaubt mehrere gleichzeitig geöffnete Konten)",
        "sec_privacy": "Datenschutz: Dieses Programm nutzt kein Internet und sendet keine Daten. Passwörter werden verschlüsselt im Tresor gespeichert (Master-Passwort) und alle Ordner des Programms sind privat (nur Sie haben Zugriff).",
        "hint_lock": "Die Sperre blendet das Fenster aus, bis das Master-Passwort eingegeben wird. Die Anmeldungen getrennter Profile liegen in den Ordnern des Clients selbst und werden von diesem Programm nicht verschlüsselt; schützen Sie sie mit einer Festplattenverschlüsselung.",
        "btn_changemaster": "Master-Passwort ändern…",
        "ask_wipe": "Dadurch werden der Tresor mit allen Konten und Passwörtern, die Profile und gespeicherten Anmeldungen, die Sitzungen, die Protokolle und die Einstellungen gelöscht. Das lässt sich nicht rückgängig machen. Fortfahren?",
        "info_wipe_done": "Alle Programmdaten wurden gelöscht. Das Programm wird jetzt geschlossen.",
        "pw_current": "Geben Sie das Master-Passwort ein:",
        "pw_confirm": "Bestätigen Sie das Master-Passwort:",
        "pw_title": "Master-Passwort",
        "pw_new": "Neues Master-Passwort (mindestens 8 Zeichen):",
        "pw_repeat": "Neues Master-Passwort wiederholen:",
        "lock_prompt": "Geben Sie das Master-Passwort ein, um fortzufahren:",
        "dlg_secret_title": "Passwort von {name}",
        "pw_none": "(kein Passwort gespeichert)",
        "import_title": "Konten importieren",
        "import_filter": "Textdateien (*.txt);;Alle Dateien (*)",
        "import_text_hint": "Fügen Sie ein Konto pro Zeile im Format Benutzer:Passwort ein.",
        "ask_overwrite_title": "Vorhandene Konten",
        "ask_overwrite": "{n} Konto/Konten existieren bereits im Tresor. Passwort durch das importierte ersetzen?",
        "export_title": "Konten exportieren",
        "ask_export": "Die exportierte Datei enthält alle Passwörter im Klartext. Fortfahren?",
        "guide_text": "1. Geben Sie unter Hinzufügen den Benutzernamen ein (und das Passwort, falls Sie es speichern möchten).\n2. Um mehrere Konten auf einmal zu übernehmen, verwenden Sie Datei > Importieren, mit einem Konto pro Zeile im Format Benutzer:Passwort. Dasselbe Format gilt für den Export.\n3. Wählen Sie das Konto aus und klicken Sie auf „Zum Anmelden öffnen“. Melden Sie sich im Client (Sober oder Mocktail) an und schließen Sie ihn. Das geschieht einmal pro Konto.\n4. Geben Sie die Spiel-ID ein (die Zahl in der URL der Spielseite auf roblox.com), wählen Sie die Konten aus und klicken Sie auf „Mit Auswahl beitreten“.\n5. Um das Passwort bei der Anmeldung einzufügen, verwenden Sie „Passwort kopieren“: Es wird nach {n} Sekunden aus der Zwischenablage gelöscht.\n\nTastenkürzel: Strg+N hinzufügen, Strg+E bearbeiten, Entf entfernen, Strg+Umschalt+C Passwort kopieren, Strg+I importieren, Strg+Umschalt+E exportieren, Strg+Enter Spiel beitreten, Strg+L sperren, Strg+, Einstellungen, F1 diese Anleitung.\n\nAlles, was passiert, erscheint auch im Terminal und in der Protokolldatei. Passwörter werden nie protokolliert.",
        "about_text": "Roblox-Kontenverwaltung {version}\nUnabhängiges Projekt ohne Verbindung zur Roblox Corporation.\nNutzt kein Internet und sendet keine Daten.",
        "cli_desc": "Roblox-Kontenverwaltung für Linux. Ohne Befehl wird die grafische Oberfläche geöffnet.",
        "cli_list": "listet die Konten auf",
        "cli_add": "fügt ein Konto hinzu",
        "cli_remove": "entfernt ein Konto",
        "cli_import": "importiert Konten aus einer Datei im Format Benutzer:Passwort",
        "cli_export": "exportiert die Konten in eine Datei im Format Benutzer:Passwort",
        "cli_launch": "öffnet den Client mit einem Konto",
        "cli_version": "zeigt die Version an",
        "cli_yes": "keine Bestätigung abfragen",
        "cli_overwrite": "ersetzt das Passwort bereits vorhandener Konten",
        "cli_force": "überschreibt die Zieldatei, falls vorhanden",
        "cli_account": "Benutzername des Kontos",
        "cli_file": "Dateipfad",
        "cli_prompt_master": "Master-Passwort: ",
        "cli_prompt_confirm": "Master-Passwort bestätigen: ",
        "cli_prompt_new": "Master-Passwort festlegen: ",
        "cli_prompt_repeat": "Master-Passwort wiederholen: ",
        "cli_prompt_pass": "Passwort (leer für keines): ",
        "cli_confirm_remove": "{name} entfernen? [j/N]: ",
        "cli_confirm_replace": "{path} existiert bereits. Ersetzen? [j/N]: ",
        "cli_confirm_overwrite": "{n} Konto/Konten existieren bereits. Passwörter ersetzen? [j/N]: ",
    },
}


_current = "en"


def resolve_language(choice="auto"):
    if choice in LANGS:
        return choice
    for variable in ("LC_ALL", "LC_MESSAGES", "LANGUAGE", "LANG"):
        value = os.environ.get(variable, "").strip().lower()
        if not value:
            continue
        for code in LANGS:
            if value.startswith(code):
                return code
        break
    return "en"


def set_language(code):
    global _current
    _current = code if code in LANGS else "en"
    return _current


def current_language():
    return _current


def translate(lang, key, **params):
    text = LANGS.get(lang, {}).get(key)
    if text is None:
        text = LANGS["en"].get(key, key)
    for name, value in params.items():
        text = text.replace("{" + name + "}", str(value))
    return text


def tr(key, **params):
    return translate(_current, key, **params)
